"use strict";
const age = 25;
let userName = "Alice";
console.log("Original userName:", userName);
userName = "sharon";
console.log("Updated userName:", userName);
let score;
score = 100;
console.log("Score:", score);
let isActive = true;
